// flow-typed signature: d659e34473a826b097228c77ca300c66
// flow-typed version: <<STUB>>/gatsby-plugin-sass_v^2.0.4/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-sass/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sass/resolve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-sass/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-sass/gatsby-node'>;
}
declare module 'gatsby-plugin-sass/index' {
  declare module.exports: $Exports<'gatsby-plugin-sass'>;
}
declare module 'gatsby-plugin-sass/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-sass'>;
}
declare module 'gatsby-plugin-sass/resolve.js' {
  declare module.exports: $Exports<'gatsby-plugin-sass/resolve'>;
}
