// flow-typed signature: 675d9d9c5e15692e5a2dfb741987d031
// flow-typed version: <<STUB>>/gatsby-plugin-eslint_v^2.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-eslint/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-eslint/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-eslint/gatsby-node'>;
}
declare module 'gatsby-plugin-eslint/index' {
  declare module.exports: $Exports<'gatsby-plugin-eslint'>;
}
declare module 'gatsby-plugin-eslint/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-eslint'>;
}
